Update for compatibility with LTS 7.15
HaskellCNOrg/snaplet-i18n pull request #2
Opened 2017-01-16 03:11 UTC by TheBizzle

This is intended to fix #1.

The only testing I've done is seeing that compilation now succeeds.  Suggestions for how to better test these changes would be welcome.

Also, I'm glad to make any changes that you'd like.

2017-01-23 02:18 UTC, freizl commented
Sorry for later response. Did you test the example from `example` folder?

2017-01-23 02:19 UTC, TheBizzle commented
I did not.  How can I do that?

2017-01-25 23:21 UTC, freizl commented
Please check the cabal file. It shall create an 'demo' execution hence I think `stack exec demo` shall work.
The execution is basically an simple snap application (web server)

2017-01-25 23:23 UTC, freizl commented
So that you could verify from an browser

2017-02-02 16:29 UTC, freizl requested changes
I did verify the changes in my local and it works well.
Would you please address those comments and I'll merge the PR?

2017-02-02 16:29 UTC, freizl commented on snaplet-i18n.cabal
> +              , map-syntax >= 0.2 && < 0.3
since we have specify particular version of `map-syntax` in the `stack.yaml`, it seems not necessary to put range here. (same below)

2017-02-02 16:29 UTC, freizl commented on stack.yaml
> -# This file was automatically generated by 'stack init'
Could you please keep those default comments but only update sections that require changes?
(resolver and extra-deps)

2017-02-02 16:57 UTC, TheBizzle commented on stack.yaml
> -# This file was automatically generated by 'stack init'
I can, but note that I did not manually edit the `stack.yaml` file.  What you see in that file is only the result of running `stack solver --update-config`.  So those comments and things can be retained, but then, every time you tell Stack to update the config, you're going to have to manually edit `stack.yaml` to keep them.

2017-02-02 17:01 UTC, TheBizzle commented on snaplet-i18n.cabal
> +              , map-syntax >= 0.2 && < 0.3
Well, I don't honestly know how the whole thing works.  I'm not very experienced at Haskell development.  But my understanding is that `stack.yaml` is generated from this `.cabal` file, so I'm not confident that I'm being redundant by having both this line and the line in `stack.yaml`, but I don't mind removing the range, if you don't like it.

2017-02-02 19:48 UTC, freizl commented on snaplet-i18n.cabal
> +              , map-syntax >= 0.2 && < 0.3
yeah, let's remove it for now.

2017-02-02 19:50 UTC, freizl commented on stack.yaml
> -# This file was automatically generated by 'stack init'
interesting. but how did you update the `extra-deps` section? I thought you manually edit it?

2017-02-02 19:51 UTC, TheBizzle commented on stack.yaml
> -# This file was automatically generated by 'stack init'
I didn't.  `stack solver` did everything. :man_shrugging:

2017-02-02 19:55 UTC, TheBizzle commented
Alright, I've updated my PR to remove the version bounds on `map-syntax`.

2017-02-02 19:56 UTC, freizl approved these changes
Thanks the PR!

2017-02-02 19:57 UTC, merged